name: 🐛 Bug report
title: 'Bug: '
description: Segnala un comportamento o una componente non funzionante 
labels: ["bug", "triage"] 
body:
- type: markdown
  attributes:
    value: |
      Grazie per aver segnalato un bug!

      Per cortesia compila attentamente il form per aiutarti meglio.
      
- type: checkboxes
  attributes:
    label: Checklist Pre volo
    description: Assicurati di aver completato tutte le azioni seguenti.
    options:
      - label: Ho cercato fra i vari problemi presenti e non ho trovato nessuna che corrisponda al mio problema.
        required: true
        
- type: textarea
  attributes:
    label: Comportamento del Bug
    description: Una descrizione di cosa accade quando succede il bug.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Comportamento Aspettato
    description: Una descrizione di cosa doveva succedere quando si è scatenato il bug.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Passi per riprodurre
    description: I passaggi da fare per riprodurre il bug.
    placeholder: |
      1. Con questo setup '...'
      2. Esegui '...'
      3. Errore causato '...'
      
- type: textarea
  attributes:
    label: Info Addizionali
    description: Links? Riferimenti? Qualsiasi cosa ti passo per la mente che possa aiutarci!