name: Export
on: 
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  Labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
  
      - name: Export Label Config
        uses: EndBug/export-label-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          raw-result: false
          add-aliases: true
      
      - name: Push Artifact Into Branch
        uses: actions/download-artifact@v2
        with:
          name: 'Label config'
          path: './labels/default'
          
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: '🔁 Generating Latest Labels [skip ci]'
          push: true
          remove: './labels/default/labels.json'