name: Export
on: 
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  Labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
  
      - name: Export Label Config
        uses: EndBug/export-label-config@dd7608994f61774a59e9011a8386ee98976328c9 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          raw-result: false
          add-aliases: true
      
      - name: Push Artifact Into Branch
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: 'Label config'
          path: './labels/default'
          
      - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        with:
          default_author: github_actions
          message: '🔁 Generating Latest Labels [skip ci]'
          push: true
          remove: './labels/default/labels.json'